# ============================================================================ #
# Proximity devphp framework config
# ============================================================================ #
admin:
  login: admin
  password: ddt4ever

# ============================================================================ #
# Database settings
# ============================================================================ #
db:
  adapter: mysqli
  host: localhost
  db: database
  user: user_name
  password: password

# ============================================================================ #
# Multilang
# ============================================================================ #
multilang:
  languages:
    nl: translationNL
    fr: translationFR

